Air gap support
cnrancher/autok3s pull request #491
Opened 2022-08-11 09:22 UTC by orangedeng

Refer to issue: https://github.com/cnrancher/autok3s/issues/448

2022-08-15 04:37 UTC, Jason-ZW requested changes

2022-08-15 04:37 UTC, Jason-ZW commented on pkg/common/package.go
> +	K3sVersion string    `json:"k3sVeersion,omitempty"`
typo

2022-08-15 04:37 UTC, Jason-ZW commented on pkg/airgap/file_scp.go
> +
remove useless line

2022-08-16 08:21 UTC, orangedeng commented
Updated

2022-08-18 01:22 UTC, merged