docs(autok3s): Add airgap install docs
cnrancher/autok3s pull request #494
Opened 2022-08-19 07:10 UTC by orangedeng

Refer to issue https://github.com/cnrancher/autok3s/issues/448

2022-08-22 03:58 UTC, Jason-ZW requested changes
Should add a link from root README.md

2022-08-22 03:58 UTC, Jason-ZW commented on docs/i18n/en_us/airgap/README.md
> +## Import&Export
Import & Export

2022-08-23 01:26 UTC, orangedeng commented on docs/i18n/en_us/airgap/README.md
> +## Import&Export
Updated

2022-08-23 01:50 UTC, Jason-ZW approved these changes

2022-11-10 02:55 UTC, merged